title: Roshan's Blog
description: Stuff I find interesting, mostly physics, hardware, AI, and neuroscience
author: Roshan Wariar
url: https://roshanwariar.github.io
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

# Exclude files from being processed
exclude:
  - .gitignore
  - README.md

# Post permalink structure
permalink: /:year/:month/:day/:title/
